//! SeaORM Entity. Generated by sea-orm-codegen 0.8.0

use super::sea_orm_active_enums::StateChangeReasonKind;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "account_changes")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(column_type = "Text")]
    pub affected_account_id: String,
    #[sea_orm(column_type = "Decimal(Some((20, 0)))")]
    pub changed_in_block_timestamp: Decimal,
    #[sea_orm(column_type = "Text")]
    pub changed_in_block_hash: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub caused_by_transaction_hash: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub caused_by_receipt_id: Option<String>,
    pub update_reason: StateChangeReasonKind,
    #[sea_orm(column_type = "Decimal(Some((45, 0)))")]
    pub affected_account_nonstaked_balance: Decimal,
    #[sea_orm(column_type = "Decimal(Some((45, 0)))")]
    pub affected_account_staked_balance: Decimal,
    #[sea_orm(column_type = "Decimal(Some((20, 0)))")]
    pub affected_account_storage_usage: Decimal,
    pub index_in_block: i32,
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl ActiveModelBehavior for ActiveModel {}
