//! SeaORM Entity. Generated by sea-orm-codegen 0.8.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "action_receipts")]
pub struct Model {
    #[sea_orm(primary_key, column_type = "Text")]
    pub receipt_id: String,
    #[sea_orm(column_type = "Text")]
    pub signer_account_id: String,
    #[sea_orm(column_type = "Text")]
    pub signer_public_key: String,
    #[sea_orm(column_type = "Decimal(Some((45, 0)))")]
    pub gas_price: Decimal,
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl ActiveModelBehavior for ActiveModel {}
