//! SeaORM Entity. Generated by sea-orm-codegen 0.8.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "aggregated__circulating_supply")]
pub struct Model {
    #[sea_orm(column_type = "Decimal(Some((20, 0)))")]
    pub computed_at_block_timestamp: Decimal,
    #[sea_orm(primary_key, column_type = "Text")]
    pub computed_at_block_hash: String,
    #[sea_orm(column_type = "Decimal(Some((45, 0)))")]
    pub circulating_tokens_supply: Decimal,
    #[sea_orm(column_type = "Decimal(Some((45, 0)))")]
    pub total_tokens_supply: Decimal,
    pub total_lockup_contracts_count: i32,
    pub unfinished_lockup_contracts_count: i32,
    #[sea_orm(column_type = "Decimal(Some((45, 0)))")]
    pub foundation_locked_tokens: Decimal,
    #[sea_orm(column_type = "Decimal(Some((45, 0)))")]
    pub lockups_locked_tokens: Decimal,
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl ActiveModelBehavior for ActiveModel {}
