//! SeaORM Entity. Generated by sea-orm-codegen 0.9.1

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize)]
#[sea_orm(table_name = "data_receipts")]
pub struct Model {
    #[sea_orm(primary_key, column_type = "Text")]
    pub data_id: String,
    #[sea_orm(primary_key, column_type = "Text")]
    pub receipt_id: String,
    pub data: Option<Vec<u8>>,
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl ActiveModelBehavior for ActiveModel {}
