//! SeaORM Entity. Generated by sea-orm-codegen 0.8.0

use super::sea_orm_active_enums::ExecutionOutcomeStatus;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "execution_outcomes")]
pub struct Model {
    #[sea_orm(primary_key, column_type = "Text")]
    pub receipt_id: String,
    #[sea_orm(column_type = "Text")]
    pub executed_in_block_hash: String,
    #[sea_orm(column_type = "Decimal(Some((20, 0)))")]
    pub executed_in_block_timestamp: Decimal,
    pub index_in_chunk: i32,
    #[sea_orm(column_type = "Decimal(Some((20, 0)))")]
    pub gas_burnt: Decimal,
    #[sea_orm(column_type = "Decimal(Some((45, 0)))")]
    pub tokens_burnt: Decimal,
    #[sea_orm(column_type = "Text")]
    pub executor_account_id: String,
    pub status: ExecutionOutcomeStatus,
    #[sea_orm(column_type = "Decimal(Some((20, 0)))")]
    pub shard_id: Decimal,
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl ActiveModelBehavior for ActiveModel {}
