//! SeaORM Entity. Generated by sea-orm-codegen 0.8.0

use super::sea_orm_active_enums::ReceiptKind;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "receipts")]
pub struct Model {
    #[sea_orm(primary_key, column_type = "Text")]
    pub receipt_id: String,
    #[sea_orm(column_type = "Text")]
    pub included_in_block_hash: String,
    #[sea_orm(column_type = "Text")]
    pub included_in_chunk_hash: String,
    pub index_in_chunk: i32,
    #[sea_orm(column_type = "Decimal(Some((20, 0)))")]
    pub included_in_block_timestamp: Decimal,
    #[sea_orm(column_type = "Text")]
    pub predecessor_account_id: String,
    #[sea_orm(column_type = "Text")]
    pub receiver_account_id: String,
    pub receipt_kind: ReceiptKind,
    #[sea_orm(column_type = "Text")]
    pub originated_from_transaction_hash: String,
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl ActiveModelBehavior for ActiveModel {}
