//! SeaORM Entity. Generated by sea-orm-codegen 0.8.0

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "nft_event_kind")]
pub enum NftEventKind {
    #[sea_orm(string_value = "BURN")]
    Burn,
    #[sea_orm(string_value = "MINT")]
    Mint,
    #[sea_orm(string_value = "TRANSFER")]
    Transfer,
}
#[derive(Debug, Clone, PartialEq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "ft_event_kind")]
pub enum FtEventKind {
    #[sea_orm(string_value = "BURN")]
    Burn,
    #[sea_orm(string_value = "MINT")]
    Mint,
    #[sea_orm(string_value = "TRANSFER")]
    Transfer,
}
#[derive(Debug, Clone, PartialEq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "receipt_kind")]
pub enum ReceiptKind {
    #[sea_orm(string_value = "ACTION")]
    Action,
    #[sea_orm(string_value = "DATA")]
    Data,
}
#[derive(Debug, Clone, PartialEq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "execution_outcome_status"
)]
pub enum ExecutionOutcomeStatus {
    #[sea_orm(string_value = "FAILURE")]
    Failure,
    #[sea_orm(string_value = "SUCCESS_RECEIPT_ID")]
    SuccessReceiptId,
    #[sea_orm(string_value = "SUCCESS_VALUE")]
    SuccessValue,
    #[sea_orm(string_value = "UNKNOWN")]
    Unknown,
}
#[derive(Debug, Clone, PartialEq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "access_key_permission_kind"
)]
pub enum AccessKeyPermissionKind {
    #[sea_orm(string_value = "FULL_ACCESS")]
    FullAccess,
    #[sea_orm(string_value = "FUNCTION_CALL")]
    FunctionCall,
}
#[derive(Debug, Clone, PartialEq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "action_kind")]
pub enum ActionKind {
    #[sea_orm(string_value = "ADD_KEY")]
    AddKey,
    #[sea_orm(string_value = "CREATE_ACCOUNT")]
    CreateAccount,
    #[sea_orm(string_value = "DELETE_ACCOUNT")]
    DeleteAccount,
    #[sea_orm(string_value = "DELETE_KEY")]
    DeleteKey,
    #[sea_orm(string_value = "DEPLOY_CONTRACT")]
    DeployContract,
    #[sea_orm(string_value = "FUNCTION_CALL")]
    FunctionCall,
    #[sea_orm(string_value = "STAKE")]
    Stake,
    #[sea_orm(string_value = "TRANSFER")]
    Transfer,
}
#[derive(Debug, Clone, PartialEq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "state_change_reason_kind"
)]
pub enum StateChangeReasonKind {
    #[sea_orm(string_value = "ACTION_RECEIPT_GAS_REWARD")]
    ActionReceiptGasReward,
    #[sea_orm(string_value = "ACTION_RECEIPT_PROCESSING_STARTED")]
    ActionReceiptProcessingStarted,
    #[sea_orm(string_value = "MIGRATION")]
    Migration,
    #[sea_orm(string_value = "POSTPONED_RECEIPT")]
    PostponedReceipt,
    #[sea_orm(string_value = "RECEIPT_PROCESSING")]
    ReceiptProcessing,
    #[sea_orm(string_value = "TRANSACTION_PROCESSING")]
    TransactionProcessing,
    #[sea_orm(string_value = "UPDATED_DELAYED_RECEIPTS")]
    UpdatedDelayedReceipts,
    #[sea_orm(string_value = "VALIDATOR_ACCOUNTS_UPDATE")]
    ValidatorAccountsUpdate,
}
